name: Deploy to BNB Testnet

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
    - run: npx hardhat compile
    - run: npx hardhat run scripts/deploy.js --network bnbTestnet
      env:
        BNB_RPC_URL: ${{ secrets.BNB_RPC_URL }}
        PRIVATE_KEY:  ${{ secrets.PRIVATE_KEY }}
name: Deploy to BNB Testnet

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
    - run: npx hardhat compile
    - run: npx hardhat run scripts/deploy.js --network bnbTestnet
      env:
        BNB_RPC_URL: ${{ secrets.BNB_RPC_URL }}
        PRIVATE_KEY:  ${{ secrets.PRIVATE_KEY }}
